#!/bin/bash

COSMOS_PATH="/home/kuba/Projects/cosmos"
COSMOS_IMAGE_PATH="$COSMOS_PATH/bin/arm-beaglebone-black/cosmos.elf"
COSMOS_GDBINIT_PATH="$COSMOS_PATH/scripts/cosmos.gdbinit"


arm-none-eabi-gdb --tui $COSMOS_IMAGE_PATH -x $COSMOS_GDBINIT_PATH
